String url = 'https://otckspuneteyxksreymo.supabase.co';
String annonKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90Y2tzcHVuZXRleXhrc3JleW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTI3NDkzNzksImV4cCI6MjAyODMyNTM3OX0.pQrWGhDB7GFxTX3jPcUujCjCEpZFMXvjbOUCqDG-tQE';
